CREATE TABLE IF NOT EXISTS "EmergencyPreferences" (
  "UserId" TEXT PRIMARY KEY,
  "SendToEmergencyContacts" BOOLEAN NOT NULL DEFAULT true,
  "SendToAmbulanceService" BOOLEAN NOT NULL DEFAULT false,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
