// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(LifeGuardDbContext))]
    [Migration("20250921160855_Reports-Adding")]
    partial class ReportsAdding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.EmergencyContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpDatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmergencyContacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 21, 16, 8, 55, 34, DateTimeKind.Utc).AddTicks(4918),
                            Email = "info@moh.gov.gh",
                            Name = "Ambulance Service",
                            Phone = "0505982870",
                            UpDatedAt = new DateTime(2025, 9, 21, 16, 8, 55, 34, DateTimeKind.Utc).AddTicks(4918),
                            UserId = "03f9a363-b1bb-4273-9b86-25772c96131f"
                        });
                });

            modelBuilder.Entity("Domain.HealthReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgAirQualityIndex")
                        .HasColumnType("integer");

                    b.Property<double>("AvgAmbientTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgDailySteps")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgPressure")
                        .HasColumnType("double precision");

                    b.Property<int>("Avgco2")
                        .HasColumnType("integer");

                    b.Property<int>("Avgpm10")
                        .HasColumnType("integer");

                    b.Property<int>("Avgpm25")
                        .HasColumnType("integer");

                    b.Property<int>("Avgvoc")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataPointCount")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FallCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Maxaqi")
                        .HasColumnType("integer");

                    b.Property<int>("Minaqi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpDatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HealthReports");
                });

            modelBuilder.Entity("Domain.Memos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpDatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Memos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 21, 16, 8, 55, 34, DateTimeKind.Utc).AddTicks(4732),
                            Done = false,
                            Text = "Hi, This is my first Memo",
                            UpDatedAt = new DateTime(2025, 9, 21, 16, 8, 55, 34, DateTimeKind.Utc).AddTicks(4734),
                            UserId = "7a223968-23b4-4652-z7b7-8574d048cdb9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
